sm8450-common: Import missing HAL
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.oplus.hardware.sendextcamcmd.ISendExtCamCmdService/default (@2)