sm8450-common: Declare missing camera Hal
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.oplus.hardware.cammidasservice@1.0::IMIDASService/default